# =============================================================================
# CONNECTOR VARIABLES - PRODUCTION
# =============================================================================
# Aplicación: PEVE
# Entorno: Production (PRO)
# Última actualización: 2024-01-XX
# Responsable: [Nombre del equipo]

# =============================================================================
# CONNECTOR CONFIGURATION (Non-Sensitive) - Environment Specific
# =============================================================================
config_nonsensitive:
  azure.eventhubs.namespace: "prod-eventhub-namespace.servicebus.windows.net"
  azure.eventhubs.hub.name: "prod-eventhub-name"
  azure.eventhubs.consumer.group: "prod-consumer-group"
  kafka.topic: "prod-topic-name"

# =============================================================================
# CONNECTOR CONFIGURATION (Sensitive) - Environment Specific
# =============================================================================
config_sensitive:
  azure.eventhubs.sas.keyname: ""  # Se obtiene desde Vault/secrets
  azure.eventhubs.sas.key: ""     # Se obtiene desde Vault/secrets

# =============================================================================
# CONNECTOR STATUS
# =============================================================================
status: "RUNNING"

