name: peve-util-triaje-cfk-mrco-desa
on:
  workflow_dispatch:
env:
#  TF_LOG: "DEBUG"
  AMBIENTE: "desa"
  SC1_DNS_SERVER_01: "10.79.228.100"
  CU1_DNS_SERVER_01: "10.166.4.36"
  EU2_DNS_SERVER_01: "10.79.228.100"

  DOMAIN_OTELCO: "azingresso11ydesaeu201.credito.bcp.com.pe"
  DOMAIN_LDAP: "balanceadorad.credito.bcp.com.pe"

jobs:
  PREPARE:
    name: "Prepare ${{ github.ref_name }}"
    runs-on: arc-runner-desa-set #self-hosted
    environment: PEVE_UTIL_CD_DESA

    steps:

      - name: Install basic tools
        run: |
          echo "ejecutando rama ${{ github.ref_name }}"
          echo "PR description: ${{ github.event.pull_request.title }}"
          echo "PR description: ${{ github.event.pull_request.base.ref }}"
          if [[ "develop-v2" != ${{ github.ref_name }} ]]; then
            echo "Este job solo esta permitido para ${{ vars.BRANCH_TARGET }}"
            exit 1
          fi
#          sudo apt-get update  > /dev/null 2>&1; sudo apt-get install wget unzip git tree ca-certificates dnsutils jq -y  > /dev/null 2>&1

  CFK_SC1:
    name: "Health check AKS CFK SC1"
    runs-on: arc-runner-desa-set
    environment: PEVE_UTIL_CD_DESA
    needs: PREPARE

    steps:

      - name: "Curl ifconfig.me"
        shell: bash
        run: |
          echo "hacer curl -s https://ifconfig.me "
          curl -s https://ifconfig.me || echo "Curl command force disconnect"

      - name: Cache de Binario kubectl
        id: cache-kubectl
        uses: actions/cache@v4
        with:
          path: ~/kubectl_bin
          key: kubectl_bin

      - name: Descargar kubectl sino existe en Cache
        if: steps.cache-kubectl.outputs.cache-hit != 'true'
        run: |
          curl -o ~/kubectl_bin -L "https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl"

      - name: Instalar kubectl
        run: |
          mkdir -p "$HOME/bin"
          ls -liah ~/kubectl_bin
          cp ~/kubectl_bin "$HOME/bin/kubectl"
          sudo chmod a+x "$HOME/bin/kubectl"
          echo "$HOME/bin" >> $GITHUB_PATH
          ls -liah "$HOME/bin/kubectl"

      - name: "get kubeconfig SC1"
        shell: bash
        env:
          ENV: ${{ env.AMBIENTE }}
          REGION: "sc1"
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.TMP_PEVE_AKS_SC1_KUBECONFIG_DESA }}" > ~/.kube/aks-${{ env.REGION }}-config-${{ env.ENV }}
          ls -lia  ~/.kube
          export KUBECONFIG=~/.kube/aks-${{ env.REGION }}-config-${{ env.ENV }}
          kubectl version
          kubectl config get-contexts
          kubectl cluster-info

      - name: "Test Dns server SC1"
        shell: bash
        env:
          ENV: ${{ env.AMBIENTE }}
          REGION: "sc1"
        run: |
          export KUBECONFIG=~/.kube/aks-${{ env.REGION }}-config-${{ env.ENV }}
          kubectl config get-contexts
          kubectl -n poc get pods --no-headers |grep kafkaclient4
          kafkaclient4_pod=$(kubectl -n poc get po --no-headers |grep kafkaclient4 | awk 'NR==1{print $1}')
          echo "Nos conectamos al Pod: $kafkaclient4_pod"
          echo "DNS: ${{ env.SC1_DNS_SERVER_01 }}"
          echo "Resolver nombre de dominio:  mcr.microsoft.com"
          kubectl -n poc exec -it $kafkaclient4_pod -- nslookup mcr.microsoft.com ${{ env.SC1_DNS_SERVER_01 }}

          echo "Resolver nombre de dominio: ${{ env.DOMAIN_LDAP }}"
          kubectl -n poc exec -it $kafkaclient4_pod -- nslookup  ${{ env.DOMAIN_LDAP }} ${{ env.SC1_DNS_SERVER_01 }}

          echo "Resolver nombre de dominio: ${{ env.DOMAIN_OTELCO }}"
          kubectl -n poc exec -it $kafkaclient4_pod -- nslookup ${{ env.DOMAIN_OTELCO }} ${{ env.SC1_DNS_SERVER_01 }}


      - name: "Curl Telnet SC1"
        shell: bash
        env:
          ENV: ${{ env.AMBIENTE }}
          REGION: "sc1"
        run: |
          export KUBECONFIG=~/.kube/aks-${{ env.REGION }}-config-${{ env.ENV }}
          kubectl config get-contexts
          kubectl -n poc get pods --no-headers |grep kafkaclient4
          kafkaclient4_pod=$(kubectl -n poc get po --no-headers |grep kafkaclient4 | awk 'NR==1{print $1}')
          echo "Nos conectamos al Pod: $kafkaclient4_pod"

          echo "hacer telnet a ${{ env.DOMAIN_OTELCO }} puerto 443 "
          kubectl -n poc exec -it $kafkaclient4_pod -- curl -v --max-time 5 telnet://${{ env.DOMAIN_OTELCO }}:443 || echo "Curl command force disconnect"

          echo "hacer telnet a mcr.microsoft.com puerto 443 "
          kubectl -n poc exec -it $kafkaclient4_pod -- curl -v --max-time 5 telnet://mcr.microsoft.com:443 || echo "Curl command force disconnect"

      - name: "View Log zookeer and Quorum "
        shell: bash
        env:
          ENV: ${{ env.AMBIENTE }}
          REGION: "sc1"
        run: |
          export KUBECONFIG=~/.kube/aks-${{ env.REGION }}-config-${{ env.ENV }}
          kubectl config get-contexts
          kubectl -n sc1 get pods
          echo "View leader zookeeper"
          kubectl -n sc1 logs zookeeper-0 |egrep -i "TOOK|Connected to leader"

  CFK_CU1:
    name: "Health check AKS CFK CU1"
    runs-on: arc-runner-desa-set
    environment: PEVE_UTIL_CD_DESA
    needs: PREPARE


    steps:
      - name: Cache de Binario kubectl
        id: cache-kubectl
        uses: actions/cache@v4
        with:
          path: ~/kubectl_bin
          key: kubectl_bin

      - name: Descargar kubectl sino existe en Cache
        if: steps.cache-kubectl.outputs.cache-hit != 'true'
        run: |
          curl -o ~/kubectl_bin -L "https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl"

      - name: Instalar kubectl
        run: |
          mkdir -p "$HOME/bin"
          ls -liah ~/kubectl_bin
          cp ~/kubectl_bin "$HOME/bin/kubectl"
          sudo chmod a+x "$HOME/bin/kubectl"
          echo "$HOME/bin" >> $GITHUB_PATH
          ls -liah "$HOME/bin/kubectl"

      - name: "get kubeconfig CU1"
        shell: bash
        env:
          ENV: ${{ env.AMBIENTE }}
          REGION: "cu1"
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.TMP_PEVE_AKS_CU1_KUBECONFIG_DESA }}" > ~/.kube/aks-${{ env.REGION }}-config-${{ env.ENV }}
          ls -lia  ~/.kube
          export KUBECONFIG=~/.kube/aks-${{ env.REGION }}-config-${{ env.ENV }}
          kubectl version
          kubectl config get-contexts
          kubectl cluster-info

      - name: "Test Dns server and LDAP CU1"
        shell: bash
        env:
          ENV: ${{ env.AMBIENTE }}
          REGION: "cu1"
        run: |
          export KUBECONFIG=~/.kube/aks-${{ env.REGION }}-config-${{ env.ENV }}
          kubectl config get-contexts
          kubectl -n poc get pods --no-headers |grep kafkaclient4
          kafkaclient4_pod=$(kubectl -n poc get po --no-headers |grep kafkaclient4 | awk 'NR==1{print $1}')
          echo "Nos conectamos al Pod: $kafkaclient4_pod"
          echo "DNS: ${{ env.CU1_DNS_SERVER_01 }}"
          echo "Resolver nombre de dominio:  mcr.microsoft.com"
          kubectl -n poc exec -it $kafkaclient4_pod -- nslookup mcr.microsoft.com ${{ env.CU1_DNS_SERVER_01 }}

          echo "Resolver nombre de dominio: ${{ env.DOMAIN_LDAP }}"
          kubectl -n poc exec -it $kafkaclient4_pod -- nslookup  ${{ env.DOMAIN_LDAP }} ${{ env.CU1_DNS_SERVER_01 }}

          echo "Resolver nombre de dominio: ${{ env.DOMAIN_OTELCO }}"
          kubectl -n poc exec -it $kafkaclient4_pod -- nslookup ${{ env.DOMAIN_OTELCO }} ${{ env.CU1_DNS_SERVER_01 }}

      - name: "Curl Telnet CU1"
        shell: bash
        env:
          ENV: ${{ env.AMBIENTE }}
          REGION: "cu1"
        run: |
          export KUBECONFIG=~/.kube/aks-${{ env.REGION }}-config-${{ env.ENV }}
          kubectl config get-contexts
          kubectl -n poc get pods --no-headers |grep kafkaclient4
          kafkaclient4_pod=$(kubectl -n poc get po --no-headers |grep kafkaclient4 | awk 'NR==1{print $1}')
          echo "Nos conectamos al Pod: $kafkaclient4_pod"

          echo "hacer telnet a ${{ env.DOMAIN_LDAP }} puerto 636 "
          kubectl -n poc exec -it $kafkaclient4_pod -- curl -v --max-time 5 telnet://${{ env.DOMAIN_LDAP }}:636 || echo "Curl command force disconnect"

          echo "hacer telnet a ${{ env.DOMAIN_OTELCO }} puerto 443 "
          kubectl -n poc exec -it $kafkaclient4_pod -- curl -v --max-time 5 telnet://${{ env.DOMAIN_OTELCO }}:443 || echo "Curl command force disconnect"

          echo "hacer telnet a mcr.microsoft.com puerto 443 "
          kubectl -n poc exec -it $kafkaclient4_pod -- curl -v --max-time 5 telnet://mcr.microsoft.com:443 || echo "Curl command force disconnect"

      - name: "View Log zookeer and Quorum "
        shell: bash
        env:
          ENV: ${{ env.AMBIENTE }}
          REGION: "cu1"
        run: |
          export KUBECONFIG=~/.kube/aks-${{ env.REGION }}-config-${{ env.ENV }}
          kubectl config get-contexts
          kubectl -n cu1 get pods
          echo "View leader zookeeper"
          kubectl -n cu1 logs zookeeper-0 |egrep -i "TOOK|Connected to leader"

  CFK_EU2:
    name: "Health check AKS CFK EU2"
    runs-on: arc-runner-desa-set
    environment: PEVE_UTIL_CD_DESA
    needs: PREPARE


    steps:
      - name: Cache de Binario kubectl
        id: cache-kubectl
        uses: actions/cache@v4
        with:
          path: ~/kubectl_bin
          key: kubectl_bin

      - name: Descargar kubectl sino existe en Cache
        if: steps.cache-kubectl.outputs.cache-hit != 'true'
        run: |
          curl -o ~/kubectl_bin -L "https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl"

      - name: Instalar kubectl
        run: |
          mkdir -p "$HOME/bin"
          ls -liah ~/kubectl_bin
          cp ~/kubectl_bin "$HOME/bin/kubectl"
          sudo chmod a+x "$HOME/bin/kubectl"
          echo "$HOME/bin" >> $GITHUB_PATH
          ls -liah "$HOME/bin/kubectl"

      - name: "get kubeconfig EU2"
        shell: bash
        env:
          ENV: ${{ env.AMBIENTE }}
          REGION: "eu2"
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.TMP_PEVE_AKS_EU2_KUBECONFIG_DESA }}" > ~/.kube/aks-${{ env.REGION }}-config-${{ env.ENV }}
          ls -lia  ~/.kube
          export KUBECONFIG=~/.kube/aks-${{ env.REGION }}-config-${{ env.ENV }}
          kubectl version
          kubectl config get-contexts
          kubectl cluster-info

      - name: "Test Dns server and LDAP EU2"
        shell: bash
        env:
          ENV: ${{ env.AMBIENTE }}
          REGION: "eu2"
        run: |
          export KUBECONFIG=~/.kube/aks-${{ env.REGION }}-config-${{ env.ENV }}
          kubectl config get-contexts
          kubectl -n poc get pods --no-headers |grep kafkaclient4
          kafkaclient4_pod=$(kubectl -n poc get po --no-headers |grep kafkaclient4 | awk 'NR==1{print $1}')
          echo "Nos conectamos al Pod: $kafkaclient4_pod"
          echo "DNS: ${{ env.EU2_DNS_SERVER_01 }}"
          echo "Resolver nombre de dominio:  mcr.microsoft.com"
          kubectl -n poc exec -it $kafkaclient4_pod -- nslookup mcr.microsoft.com ${{ env.EU2_DNS_SERVER_01 }}

          echo "Resolver nombre de dominio: ${{ env.DOMAIN_LDAP }}"
          kubectl -n poc exec -it $kafkaclient4_pod -- nslookup  ${{ env.DOMAIN_LDAP }} ${{ env.EU2_DNS_SERVER_01 }}

          echo "Resolver nombre de dominio: ${{ env.DOMAIN_OTELCO }}"
          kubectl -n poc exec -it $kafkaclient4_pod -- nslookup ${{ env.DOMAIN_OTELCO }} ${{ env.EU2_DNS_SERVER_01 }}


      - name: "Curl Telnet EU2"
        shell: bash
        env:
          ENV: ${{ env.AMBIENTE }}
          REGION: "eu2"
        run: |
          export KUBECONFIG=~/.kube/aks-${{ env.REGION }}-config-${{ env.ENV }}
          kubectl config get-contexts
          kubectl -n poc get pods --no-headers |grep kafkaclient4
          kafkaclient4_pod=$(kubectl -n poc get po --no-headers |grep kafkaclient4 | awk 'NR==1{print $1}')
          echo "Nos conectamos al Pod: $kafkaclient4_pod"

          echo "hacer telnet a ${{ env.DOMAIN_LDAP }} puerto 636 "
          kubectl -n poc exec -it $kafkaclient4_pod -- curl -v --max-time 5 telnet://${{ env.DOMAIN_LDAP }}:636 || echo "Curl command force disconnect"

          echo "hacer telnet a ${{ env.DOMAIN_OTELCO }} puerto 443 "
          kubectl -n poc exec -it $kafkaclient4_pod -- curl -v --max-time 5 telnet://${{ env.DOMAIN_OTELCO }}:443 || echo "Curl command force disconnect"

          echo "hacer telnet a mcr.microsoft.com puerto 443 "
          kubectl -n poc exec -it $kafkaclient4_pod -- curl -v --max-time 5 telnet://mcr.microsoft.com:443 || echo "Curl command force disconnect"

      - name: "View Log zookeer and Quorum "
        shell: bash
        env:
          ENV: ${{ env.AMBIENTE }}
          REGION: "eu2"
        run: |
          export KUBECONFIG=~/.kube/aks-${{ env.REGION }}-config-${{ env.ENV }}
          kubectl config get-contexts
          kubectl -n eu2 get pods
          echo "View leader zookeeper"
          kubectl -n eu2 logs zookeeper-0 |egrep -i "TOOK|Connected to leader"

