name: conector-mqzos-desa
on:
  workflow_dispatch:
    inputs:
      conector_accion:
        description: "[DESA] Selecciona la accion a realizar:"
        required: true
        type: choice
        options:
          - list
        default: "list"
jobs:
  CI_HV:
    name: "CI/CD - ${{ github.event.inputs.conector_region }}/${{ github.event.inputs.conector_accion }}"
    runs-on: "arc-runner-prod-set" #self-hosted
    environment: PEVE_DESA_UTIL
    
    steps:

      - name: Install basic tools
        run: |
          if [[ "${{ vars.BRANCH_TARGET }}" != ${{ github.ref_name }} ]]; then
            echo "Este job solo esta permitido para ${{ vars.BRANCH_TARGET }}"
            exit 1
          fi

