all:
  children:
    ocp_delivery_secret:
      hosts:
        localhost:
          ocp_hosts_dev_int: "https://ocpmasterdesa.credito.bcp.com.pe:8443"
          ocp_hosts_cert_int: "https://ocpchmastercert.credito.bcp.com.pe:8443,https://ocplmmastercert.credito.bcp.com.pe:8443"
          ocp_hosts_prod_int: "https://ocpchintmaster.lima.bcp.com.pe:8443,https://ocplmintmaster.lima.bcp.com.pe:8443"
          ocp_hosts_prod_tan: "https://ocpchtanmaster.lima.bcp.com.pe:8443,https://ocplmtanmaster.lima.bcp.com.pe:8443"
###############################################################################
# docker host groups for build-docker role
###############################################################################
    docker_local_dev:
      hosts:
        localhost:
          master_ocp_url: "https://api.ocpachdev.lima.bcp.com.pe:6443"
          ocp_docker_registry: "default-route-openshift-image-registry.apps.ocpachdev.lima.bcp.com.pe"
    docker_local_cert:
      hosts:
        localhost:
          master_ocp_url_chorrillo: "https://api.ocpachcer.lima.bcp.com.pe:6443"
          master_ocp_url_lamolina: "https://api.ocpalmcer.lima.bcp.com.pe:6443"
          ocp_docker_registry_chorrillo: "default-route-openshift-image-registry.apps.ocpachcer.lima.bcp.com.pe"
          ocp_docker_registry_lamolina:  "default-route-openshift-image-registry.apps.ocpalmcer.lima.bcp.com.pe"
#============================================================================
# docker host groups for build-docker role with production internal network
#============================================================================
    docker_local_prod:
      hosts:
        localhost:
          master_ocp_url_int_chorrillo: "https://api.ocpach.lima.bcp.com.pe:6443"
          master_ocp_url_int_lamolina: "https://api.ocpalm.lima.bcp.com.pe:6443"
          ocp_docker_registry_int_chorrillo: "default-route-openshift-image-registry.apps.ocpach.lima.bcp.com.pe"
          ocp_docker_registry_int_lamolina:  "default-route-openshift-image-registry.apps.ocpach.lima.bcp.com.pe"
###############################################################################
# hosts groups for delivery-k8s roles
###############################################################################
#============================================================================
# development
#============================================================================
    ocp_dev:
      hosts:
        ocp_dev_chorrillos:
          ansible_host: localhost
          master_ocp_url: "https://api.ocpachdev.lima.bcp.com.pe:6443"
          ocp_docker_registry: "default-route-openshift-image-registry.apps.ocpachdev.lima.bcp.com.pe"
          bootstrap_servers: "ppevesod03.kafka-desa-onprem.credito.bcp.com.pe:9092,ppevesod04.kafka-desa-onprem.credito.bcp.com.pe:9092,ppevesod05.kafka-desa-onprem.credito.bcp.com.pe:9092"
          ocp_docker_registry_deploy: "image-registry.openshift-image-registry.svc:5000"
          envkafka: cho
#============================================================================
# certification
#============================================================================ 
    ocp_cert:
      hosts:
        ocp_cert_chorrillos:
          ansible_host: localhost
          master_ocp_url: "https://api.ocpachcer.lima.bcp.com.pe:6443"
          ocp_docker_registry: "default-route-openshift-image-registry.apps.ocpachcer.lima.bcp.com.pe"
          bootstrap_servers: "ppevesoc03.kafka-cert-onprem.credito.bcp.com.pe:9092,ppevesoc04.kafka-cert-onprem.credito.bcp.com.pe:9092,ppevesoc05.kafka-cert-onprem.credito.bcp.com.pe:9092"
          ocp_docker_registry_deploy: "image-registry.openshift-image-registry.svc:5000"
          envkafka: cho
        ocp_cert_lamolina:
          ansible_host: localhost
          master_ocp_url: "https://api.ocpalmcer.lima.bcp.com.pe:6443"
          ocp_docker_registry: "default-route-openshift-image-registry.apps.ocpalmcer.lima.bcp.com.pe"
          bootstrap_servers: "ppevesoc03.kafka-cert-onprem.credito.bcp.com.pe:9092,ppevesoc04.kafka-cert-onprem.credito.bcp.com.pe:9092,ppevesoc05.kafka-cert-onprem.credito.bcp.com.pe:9092"
          ocp_docker_registry_deploy: "image-registry.openshift-image-registry.svc:5000"
          envkafka: lmo
#============================================================================
# production
#============================================================================
    ocp_prod:
      hosts:
        ocp_prod_chorrillos:
          ansible_host: localhost
          master_ocp_url: "https://api.ocpach.lima.bcp.com.pe:6443"
          ocp_docker_registry: "default-route-openshift-image-registry.apps.ocpach.lima.bcp.com.pe"
          bootstrap_servers: "ppevesop04.kafka-prod-onprem.credito.bcp.com.pe:9092,ppevesop05.kafka-prod-onprem.credito.bcp.com.pe:9092,ppevesop06.kafka-prod-onprem.credito.bcp.com.pe:9092,ppevesop07.kafka-prod-onprem.credito.bcp.com.pe:9092"
          ocp_docker_registry_deploy: "image-registry.openshift-image-registry.svc:5000"
          envkafka: cho
        ocp_prod_lamolina:
          ansible_host: localhost
          master_ocp_url: "https://api.ocpalm.lima.bcp.com.pe:6443"
          ocp_docker_registry: "default-route-openshift-image-registry.apps.ocpalm.lima.bcp.com.pe"
          bootstrap_servers: "ppevesop04.kafka-prod-onprem.credito.bcp.com.pe:9092,ppevesop05.kafka-prod-onprem.credito.bcp.com.pe:9092,ppevesop06.kafka-prod-onprem.credito.bcp.com.pe:9092,ppevesop07.kafka-prod-onprem.credito.bcp.com.pe:9092"
          ocp_docker_registry_deploy: "image-registry.openshift-image-registry.svc:5000"
          envkafka: lmo
      vars:
        ocp_app_domain: "ocpintapps.lima.bcp.com.pe"
###############################################################################
# hosts groups for delivery-k8s AKS
###############################################################################
    aks_dev:
      hosts:
        aks_dev_eu2:
          ansible_host: localhost
    aks_cert:
      hosts:
        aks_cert_eu2:
          ansible_host: localhost
    aks_prod:
      hosts:
        aks_prod_eu2:
          ansible_host: localhost

