/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.bcp.atlas.core.starter.audit.model.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;
// Avro Audit 2.5
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroAudit extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3809145471082359725L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroAudit\",\"namespace\":\"com.bcp.atlas.core.starter.audit.model.avro\",\"fields\":[{\"name\":\"eventId\",\"type\":\"string\"},{\"name\":\"requestId\",\"type\":\"string\"},{\"name\":\"requestDate\",\"type\":[\"string\",\"null\"]},{\"name\":\"channel\",\"type\":\"string\"},{\"name\":\"eventType\",\"type\":\"string\",\"aliases\":[\"type\"]},{\"name\":\"entityType\",\"type\":\"string\"},{\"name\":\"entityId\",\"type\":[\"string\",\"null\"]},{\"name\":\"applicationGroup\",\"type\":\"string\"},{\"name\":\"scopes\",\"type\":[\"null\",{\"type\":\"array\",\"items\":\"string\"}],\"default\":null},{\"name\":\"result\",\"type\":\"string\"},{\"name\":\"errorReason\",\"type\":[\"string\",\"null\"]},{\"name\":\"data\",\"type\":{\"type\":\"map\",\"values\":[\"string\",\"null\"]}},{\"name\":\"externalData\",\"type\":[\"null\",{\"type\":\"map\",\"values\":\"string\"}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AvroAudit> ENCODER =
          new BinaryMessageEncoder<AvroAudit>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AvroAudit> DECODER =
          new BinaryMessageDecoder<AvroAudit>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<AvroAudit> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<AvroAudit> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AvroAudit>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this AvroAudit to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a AvroAudit from a ByteBuffer. */
  public static AvroAudit fromByteBuffer(
          java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence eventId;
  @Deprecated public java.lang.CharSequence requestId;
  @Deprecated public java.lang.CharSequence requestDate;
  @Deprecated public java.lang.CharSequence channel;
  @Deprecated public java.lang.CharSequence eventType;
  @Deprecated public java.lang.CharSequence entityType;
  @Deprecated public java.lang.CharSequence entityId;
  @Deprecated public java.lang.CharSequence applicationGroup;
  @Deprecated public java.util.List<java.lang.CharSequence> scopes;
  @Deprecated public java.lang.CharSequence result;
  @Deprecated public java.lang.CharSequence errorReason;
  @Deprecated public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> data;
  @Deprecated public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> externalData;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroAudit() {}

  /**
   * All-args constructor.
   * @param eventId The new value for eventId
   * @param requestId The new value for requestId
   * @param requestDate The new value for requestDate
   * @param channel The new value for channel
   * @param eventType The new value for eventType
   * @param entityType The new value for entityType
   * @param entityId The new value for entityId
   * @param applicationGroup The new value for applicationGroup
   * @param scopes The new value for scopes
   * @param result The new value for result
   * @param errorReason The new value for errorReason
   * @param data The new value for data
   * @param externalData The new value for externalData
   */
  public AvroAudit(java.lang.CharSequence eventId, java.lang.CharSequence requestId, java.lang.CharSequence requestDate, java.lang.CharSequence channel, java.lang.CharSequence eventType, java.lang.CharSequence entityType, java.lang.CharSequence entityId, java.lang.CharSequence applicationGroup, java.util.List<java.lang.CharSequence> scopes, java.lang.CharSequence result, java.lang.CharSequence errorReason, java.util.Map<java.lang.CharSequence,java.lang.CharSequence> data, java.util.Map<java.lang.CharSequence,java.lang.CharSequence> externalData) {
    this.eventId = eventId;
    this.requestId = requestId;
    this.requestDate = requestDate;
    this.channel = channel;
    this.eventType = eventType;
    this.entityType = entityType;
    this.entityId = entityId;
    this.applicationGroup = applicationGroup;
    this.scopes = scopes;
    this.result = result;
    this.errorReason = errorReason;
    this.data = data;
    this.externalData = externalData;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
      case 0: return eventId;
      case 1: return requestId;
      case 2: return requestDate;
      case 3: return channel;
      case 4: return eventType;
      case 5: return entityType;
      case 6: return entityId;
      case 7: return applicationGroup;
      case 8: return scopes;
      case 9: return result;
      case 10: return errorReason;
      case 11: return data;
      case 12: return externalData;
      default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
      case 0: eventId = (java.lang.CharSequence)value$; break;
      case 1: requestId = (java.lang.CharSequence)value$; break;
      case 2: requestDate = (java.lang.CharSequence)value$; break;
      case 3: channel = (java.lang.CharSequence)value$; break;
      case 4: eventType = (java.lang.CharSequence)value$; break;
      case 5: entityType = (java.lang.CharSequence)value$; break;
      case 6: entityId = (java.lang.CharSequence)value$; break;
      case 7: applicationGroup = (java.lang.CharSequence)value$; break;
      case 8: scopes = (java.util.List<java.lang.CharSequence>)value$; break;
      case 9: result = (java.lang.CharSequence)value$; break;
      case 10: errorReason = (java.lang.CharSequence)value$; break;
      case 11: data = (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>)value$; break;
      case 12: externalData = (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>)value$; break;
      default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'eventId' field.
   * @return The value of the 'eventId' field.
   */
  public java.lang.CharSequence getEventId() {
    return eventId;
  }

  /**
   * Sets the value of the 'eventId' field.
   * @param value the value to set.
   */
  public void setEventId(java.lang.CharSequence value) {
    this.eventId = value;
  }

  /**
   * Gets the value of the 'requestId' field.
   * @return The value of the 'requestId' field.
   */
  public java.lang.CharSequence getRequestId() {
    return requestId;
  }

  /**
   * Sets the value of the 'requestId' field.
   * @param value the value to set.
   */
  public void setRequestId(java.lang.CharSequence value) {
    this.requestId = value;
  }

  /**
   * Gets the value of the 'requestDate' field.
   * @return The value of the 'requestDate' field.
   */
  public java.lang.CharSequence getRequestDate() {
    return requestDate;
  }

  /**
   * Sets the value of the 'requestDate' field.
   * @param value the value to set.
   */
  public void setRequestDate(java.lang.CharSequence value) {
    this.requestDate = value;
  }

  /**
   * Gets the value of the 'channel' field.
   * @return The value of the 'channel' field.
   */
  public java.lang.CharSequence getChannel() {
    return channel;
  }

  /**
   * Sets the value of the 'channel' field.
   * @param value the value to set.
   */
  public void setChannel(java.lang.CharSequence value) {
    this.channel = value;
  }

  /**
   * Gets the value of the 'eventType' field.
   * @return The value of the 'eventType' field.
   */
  public java.lang.CharSequence getEventType() {
    return eventType;
  }

  /**
   * Sets the value of the 'eventType' field.
   * @param value the value to set.
   */
  public void setEventType(java.lang.CharSequence value) {
    this.eventType = value;
  }

  /**
   * Gets the value of the 'entityType' field.
   * @return The value of the 'entityType' field.
   */
  public java.lang.CharSequence getEntityType() {
    return entityType;
  }

  /**
   * Sets the value of the 'entityType' field.
   * @param value the value to set.
   */
  public void setEntityType(java.lang.CharSequence value) {
    this.entityType = value;
  }

  /**
   * Gets the value of the 'entityId' field.
   * @return The value of the 'entityId' field.
   */
  public java.lang.CharSequence getEntityId() {
    return entityId;
  }

  /**
   * Sets the value of the 'entityId' field.
   * @param value the value to set.
   */
  public void setEntityId(java.lang.CharSequence value) {
    this.entityId = value;
  }

  /**
   * Gets the value of the 'applicationGroup' field.
   * @return The value of the 'applicationGroup' field.
   */
  public java.lang.CharSequence getApplicationGroup() {
    return applicationGroup;
  }

  /**
   * Sets the value of the 'applicationGroup' field.
   * @param value the value to set.
   */
  public void setApplicationGroup(java.lang.CharSequence value) {
    this.applicationGroup = value;
  }

  /**
   * Gets the value of the 'scopes' field.
   * @return The value of the 'scopes' field.
   */
  public java.util.List<java.lang.CharSequence> getScopes() {
    return scopes;
  }

  /**
   * Sets the value of the 'scopes' field.
   * @param value the value to set.
   */
  public void setScopes(java.util.List<java.lang.CharSequence> value) {
    this.scopes = value;
  }

  /**
   * Gets the value of the 'result' field.
   * @return The value of the 'result' field.
   */
  public java.lang.CharSequence getResult() {
    return result;
  }

  /**
   * Sets the value of the 'result' field.
   * @param value the value to set.
   */
  public void setResult(java.lang.CharSequence value) {
    this.result = value;
  }

  /**
   * Gets the value of the 'errorReason' field.
   * @return The value of the 'errorReason' field.
   */
  public java.lang.CharSequence getErrorReason() {
    return errorReason;
  }

  /**
   * Sets the value of the 'errorReason' field.
   * @param value the value to set.
   */
  public void setErrorReason(java.lang.CharSequence value) {
    this.errorReason = value;
  }

  /**
   * Gets the value of the 'data' field.
   * @return The value of the 'data' field.
   */
  public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getData() {
    return data;
  }

  /**
   * Sets the value of the 'data' field.
   * @param value the value to set.
   */
  public void setData(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
    this.data = value;
  }

  /**
   * Gets the value of the 'externalData' field.
   * @return The value of the 'externalData' field.
   */
  public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getExternalData() {
    return externalData;
  }

  /**
   * Sets the value of the 'externalData' field.
   * @param value the value to set.
   */
  public void setExternalData(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
    this.externalData = value;
  }

  /**
   * Creates a new AvroAudit RecordBuilder.
   * @return A new AvroAudit RecordBuilder
   */
  public static com.bcp.atlas.core.starter.audit.model.avro.AvroAudit.Builder newBuilder() {
    return new com.bcp.atlas.core.starter.audit.model.avro.AvroAudit.Builder();
  }

  /**
   * Creates a new AvroAudit RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroAudit RecordBuilder
   */
  public static com.bcp.atlas.core.starter.audit.model.avro.AvroAudit.Builder newBuilder(com.bcp.atlas.core.starter.audit.model.avro.AvroAudit.Builder other) {
    return new com.bcp.atlas.core.starter.audit.model.avro.AvroAudit.Builder(other);
  }

  /**
   * Creates a new AvroAudit RecordBuilder by copying an existing AvroAudit instance.
   * @param other The existing instance to copy.
   * @return A new AvroAudit RecordBuilder
   */
  public static com.bcp.atlas.core.starter.audit.model.avro.AvroAudit.Builder newBuilder(com.bcp.atlas.core.starter.audit.model.avro.AvroAudit other) {
    return new com.bcp.atlas.core.starter.audit.model.avro.AvroAudit.Builder(other);
  }

  /**
   * RecordBuilder for AvroAudit instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroAudit>
          implements org.apache.avro.data.RecordBuilder<AvroAudit> {

    private java.lang.CharSequence eventId;
    private java.lang.CharSequence requestId;
    private java.lang.CharSequence requestDate;
    private java.lang.CharSequence channel;
    private java.lang.CharSequence eventType;
    private java.lang.CharSequence entityType;
    private java.lang.CharSequence entityId;
    private java.lang.CharSequence applicationGroup;
    private java.util.List<java.lang.CharSequence> scopes;
    private java.lang.CharSequence result;
    private java.lang.CharSequence errorReason;
    private java.util.Map<java.lang.CharSequence,java.lang.CharSequence> data;
    private java.util.Map<java.lang.CharSequence,java.lang.CharSequence> externalData;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.bcp.atlas.core.starter.audit.model.avro.AvroAudit.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.requestId)) {
        this.requestId = data().deepCopy(fields()[1].schema(), other.requestId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.requestDate)) {
        this.requestDate = data().deepCopy(fields()[2].schema(), other.requestDate);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.channel)) {
        this.channel = data().deepCopy(fields()[3].schema(), other.channel);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.eventType)) {
        this.eventType = data().deepCopy(fields()[4].schema(), other.eventType);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.entityType)) {
        this.entityType = data().deepCopy(fields()[5].schema(), other.entityType);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.entityId)) {
        this.entityId = data().deepCopy(fields()[6].schema(), other.entityId);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.applicationGroup)) {
        this.applicationGroup = data().deepCopy(fields()[7].schema(), other.applicationGroup);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.scopes)) {
        this.scopes = data().deepCopy(fields()[8].schema(), other.scopes);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.result)) {
        this.result = data().deepCopy(fields()[9].schema(), other.result);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.errorReason)) {
        this.errorReason = data().deepCopy(fields()[10].schema(), other.errorReason);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.data)) {
        this.data = data().deepCopy(fields()[11].schema(), other.data);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.externalData)) {
        this.externalData = data().deepCopy(fields()[12].schema(), other.externalData);
        fieldSetFlags()[12] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing AvroAudit instance
     * @param other The existing instance to copy.
     */
    private Builder(com.bcp.atlas.core.starter.audit.model.avro.AvroAudit other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.eventId)) {
        this.eventId = data().deepCopy(fields()[0].schema(), other.eventId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.requestId)) {
        this.requestId = data().deepCopy(fields()[1].schema(), other.requestId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.requestDate)) {
        this.requestDate = data().deepCopy(fields()[2].schema(), other.requestDate);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.channel)) {
        this.channel = data().deepCopy(fields()[3].schema(), other.channel);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.eventType)) {
        this.eventType = data().deepCopy(fields()[4].schema(), other.eventType);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.entityType)) {
        this.entityType = data().deepCopy(fields()[5].schema(), other.entityType);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.entityId)) {
        this.entityId = data().deepCopy(fields()[6].schema(), other.entityId);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.applicationGroup)) {
        this.applicationGroup = data().deepCopy(fields()[7].schema(), other.applicationGroup);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.scopes)) {
        this.scopes = data().deepCopy(fields()[8].schema(), other.scopes);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.result)) {
        this.result = data().deepCopy(fields()[9].schema(), other.result);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.errorReason)) {
        this.errorReason = data().deepCopy(fields()[10].schema(), other.errorReason);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.data)) {
        this.data = data().deepCopy(fields()[11].schema(), other.data);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.externalData)) {
        this.externalData = data().deepCopy(fields()[12].schema(), other.externalData);
        fieldSetFlags()[12] = true;
      }
    }

    /**
     * Gets the value of the 'eventId' field.
     * @return The value.
     */
    public java.lang.CharSequence getEventId() {
      return eventId;
    }

    /**
     * Sets the value of the 'eventId' field.
     * @param value The value of 'eventId'.
     * @return This builder.
     */
    public com.bcp.atlas.core.starter.audit.model.avro.AvroAudit.Builder setEventId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.eventId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
     * Checks whether the 'eventId' field has been set.
     * @return True if the 'eventId' field has been set, false otherwise.
     */
    public boolean hasEventId() {
      return fieldSetFlags()[0];
    }


    /**
     * Clears the value of the 'eventId' field.
     * @return This builder.
     */
    public com.bcp.atlas.core.starter.audit.model.avro.AvroAudit.Builder clearEventId() {
      eventId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
     * Gets the value of the 'requestId' field.
     * @return The value.
     */
    public java.lang.CharSequence getRequestId() {
      return requestId;
    }

    /**
     * Sets the value of the 'requestId' field.
     * @param value The value of 'requestId'.
     * @return This builder.
     */
    public com.bcp.atlas.core.starter.audit.model.avro.AvroAudit.Builder setRequestId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.requestId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
     * Checks whether the 'requestId' field has been set.
     * @return True if the 'requestId' field has been set, false otherwise.
     */
    public boolean hasRequestId() {
      return fieldSetFlags()[1];
    }


    /**
     * Clears the value of the 'requestId' field.
     * @return This builder.
     */
    public com.bcp.atlas.core.starter.audit.model.avro.AvroAudit.Builder clearRequestId() {
      requestId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
     * Gets the value of the 'requestDate' field.
     * @return The value.
     */
    public java.lang.CharSequence getRequestDate() {
      return requestDate;
    }

    /**
     * Sets the value of the 'requestDate' field.
     * @param value The value of 'requestDate'.
     * @return This builder.
     */
    public com.bcp.atlas.core.starter.audit.model.avro.AvroAudit.Builder setRequestDate(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.requestDate = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
     * Checks whether the 'requestDate' field has been set.
     * @return True if the 'requestDate' field has been set, false otherwise.
     */
    public boolean hasRequestDate() {
      return fieldSetFlags()[2];
    }


    /**
     * Clears the value of the 'requestDate' field.
     * @return This builder.
     */
    public com.bcp.atlas.core.starter.audit.model.avro.AvroAudit.Builder clearRequestDate() {
      requestDate = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
     * Gets the value of the 'channel' field.
     * @return The value.
     */
    public java.lang.CharSequence getChannel() {
      return channel;
    }

    /**
     * Sets the value of the 'channel' field.
     * @param value The value of 'channel'.
     * @return This builder.
     */
    public com.bcp.atlas.core.starter.audit.model.avro.AvroAudit.Builder setChannel(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.channel = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
     * Checks whether the 'channel' field has been set.
     * @return True if the 'channel' field has been set, false otherwise.
     */
    public boolean hasChannel() {
      return fieldSetFlags()[3];
    }


    /**
     * Clears the value of the 'channel' field.
     * @return This builder.
     */
    public com.bcp.atlas.core.starter.audit.model.avro.AvroAudit.Builder clearChannel() {
      channel = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
     * Gets the value of the 'eventType' field.
     * @return The value.
     */
    public java.lang.CharSequence getEventType() {
      return eventType;
    }

    /**
     * Sets the value of the 'eventType' field.
     * @param value The value of 'eventType'.
     * @return This builder.
     */
    public com.bcp.atlas.core.starter.audit.model.avro.AvroAudit.Builder setEventType(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.eventType = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
     * Checks whether the 'eventType' field has been set.
     * @return True if the 'eventType' field has been set, false otherwise.
     */
    public boolean hasEventType() {
      return fieldSetFlags()[4];
    }


    /**
     * Clears the value of the 'eventType' field.
     * @return This builder.
     */
    public com.bcp.atlas.core.starter.audit.model.avro.AvroAudit.Builder clearEventType() {
      eventType = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
     * Gets the value of the 'entityType' field.
     * @return The value.
     */
    public java.lang.CharSequence getEntityType() {
      return entityType;
    }

    /**
     * Sets the value of the 'entityType' field.
     * @param value The value of 'entityType'.
     * @return This builder.
     */
    public com.bcp.atlas.core.starter.audit.model.avro.AvroAudit.Builder setEntityType(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.entityType = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
     * Checks whether the 'entityType' field has been set.
     * @return True if the 'entityType' field has been set, false otherwise.
     */
    public boolean hasEntityType() {
      return fieldSetFlags()[5];
    }


    /**
     * Clears the value of the 'entityType' field.
     * @return This builder.
     */
    public com.bcp.atlas.core.starter.audit.model.avro.AvroAudit.Builder clearEntityType() {
      entityType = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
     * Gets the value of the 'entityId' field.
     * @return The value.
     */
    public java.lang.CharSequence getEntityId() {
      return entityId;
    }

    /**
     * Sets the value of the 'entityId' field.
     * @param value The value of 'entityId'.
     * @return This builder.
     */
    public com.bcp.atlas.core.starter.audit.model.avro.AvroAudit.Builder setEntityId(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.entityId = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
     * Checks whether the 'entityId' field has been set.
     * @return True if the 'entityId' field has been set, false otherwise.
     */
    public boolean hasEntityId() {
      return fieldSetFlags()[6];
    }


    /**
     * Clears the value of the 'entityId' field.
     * @return This builder.
     */
    public com.bcp.atlas.core.starter.audit.model.avro.AvroAudit.Builder clearEntityId() {
      entityId = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
     * Gets the value of the 'applicationGroup' field.
     * @return The value.
     */
    public java.lang.CharSequence getApplicationGroup() {
      return applicationGroup;
    }

    /**
     * Sets the value of the 'applicationGroup' field.
     * @param value The value of 'applicationGroup'.
     * @return This builder.
     */
    public com.bcp.atlas.core.starter.audit.model.avro.AvroAudit.Builder setApplicationGroup(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.applicationGroup = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
     * Checks whether the 'applicationGroup' field has been set.
     * @return True if the 'applicationGroup' field has been set, false otherwise.
     */
    public boolean hasApplicationGroup() {
      return fieldSetFlags()[7];
    }


    /**
     * Clears the value of the 'applicationGroup' field.
     * @return This builder.
     */
    public com.bcp.atlas.core.starter.audit.model.avro.AvroAudit.Builder clearApplicationGroup() {
      applicationGroup = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
     * Gets the value of the 'scopes' field.
     * @return The value.
     */
    public java.util.List<java.lang.CharSequence> getScopes() {
      return scopes;
    }

    /**
     * Sets the value of the 'scopes' field.
     * @param value The value of 'scopes'.
     * @return This builder.
     */
    public com.bcp.atlas.core.starter.audit.model.avro.AvroAudit.Builder setScopes(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[8], value);
      this.scopes = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
     * Checks whether the 'scopes' field has been set.
     * @return True if the 'scopes' field has been set, false otherwise.
     */
    public boolean hasScopes() {
      return fieldSetFlags()[8];
    }


    /**
     * Clears the value of the 'scopes' field.
     * @return This builder.
     */
    public com.bcp.atlas.core.starter.audit.model.avro.AvroAudit.Builder clearScopes() {
      scopes = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
     * Gets the value of the 'result' field.
     * @return The value.
     */
    public java.lang.CharSequence getResult() {
      return result;
    }

    /**
     * Sets the value of the 'result' field.
     * @param value The value of 'result'.
     * @return This builder.
     */
    public com.bcp.atlas.core.starter.audit.model.avro.AvroAudit.Builder setResult(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.result = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
     * Checks whether the 'result' field has been set.
     * @return True if the 'result' field has been set, false otherwise.
     */
    public boolean hasResult() {
      return fieldSetFlags()[9];
    }


    /**
     * Clears the value of the 'result' field.
     * @return This builder.
     */
    public com.bcp.atlas.core.starter.audit.model.avro.AvroAudit.Builder clearResult() {
      result = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
     * Gets the value of the 'errorReason' field.
     * @return The value.
     */
    public java.lang.CharSequence getErrorReason() {
      return errorReason;
    }

    /**
     * Sets the value of the 'errorReason' field.
     * @param value The value of 'errorReason'.
     * @return This builder.
     */
    public com.bcp.atlas.core.starter.audit.model.avro.AvroAudit.Builder setErrorReason(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.errorReason = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
     * Checks whether the 'errorReason' field has been set.
     * @return True if the 'errorReason' field has been set, false otherwise.
     */
    public boolean hasErrorReason() {
      return fieldSetFlags()[10];
    }


    /**
     * Clears the value of the 'errorReason' field.
     * @return This builder.
     */
    public com.bcp.atlas.core.starter.audit.model.avro.AvroAudit.Builder clearErrorReason() {
      errorReason = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
     * Gets the value of the 'data' field.
     * @return The value.
     */
    public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getData() {
      return data;
    }

    /**
     * Sets the value of the 'data' field.
     * @param value The value of 'data'.
     * @return This builder.
     */
    public com.bcp.atlas.core.starter.audit.model.avro.AvroAudit.Builder setData(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
      validate(fields()[11], value);
      this.data = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
     * Checks whether the 'data' field has been set.
     * @return True if the 'data' field has been set, false otherwise.
     */
    public boolean hasData() {
      return fieldSetFlags()[11];
    }


    /**
     * Clears the value of the 'data' field.
     * @return This builder.
     */
    public com.bcp.atlas.core.starter.audit.model.avro.AvroAudit.Builder clearData() {
      data = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
     * Gets the value of the 'externalData' field.
     * @return The value.
     */
    public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getExternalData() {
      return externalData;
    }

    /**
     * Sets the value of the 'externalData' field.
     * @param value The value of 'externalData'.
     * @return This builder.
     */
    public com.bcp.atlas.core.starter.audit.model.avro.AvroAudit.Builder setExternalData(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
      validate(fields()[12], value);
      this.externalData = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
     * Checks whether the 'externalData' field has been set.
     * @return True if the 'externalData' field has been set, false otherwise.
     */
    public boolean hasExternalData() {
      return fieldSetFlags()[12];
    }


    /**
     * Clears the value of the 'externalData' field.
     * @return This builder.
     */
    public com.bcp.atlas.core.starter.audit.model.avro.AvroAudit.Builder clearExternalData() {
      externalData = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AvroAudit build() {
      try {
        AvroAudit record = new AvroAudit();
        record.eventId = fieldSetFlags()[0] ? this.eventId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.requestId = fieldSetFlags()[1] ? this.requestId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.requestDate = fieldSetFlags()[2] ? this.requestDate : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.channel = fieldSetFlags()[3] ? this.channel : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.eventType = fieldSetFlags()[4] ? this.eventType : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.entityType = fieldSetFlags()[5] ? this.entityType : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.entityId = fieldSetFlags()[6] ? this.entityId : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.applicationGroup = fieldSetFlags()[7] ? this.applicationGroup : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.scopes = fieldSetFlags()[8] ? this.scopes : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[8]);
        record.result = fieldSetFlags()[9] ? this.result : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.errorReason = fieldSetFlags()[10] ? this.errorReason : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.data = fieldSetFlags()[11] ? this.data : (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>) defaultValue(fields()[11]);
        record.externalData = fieldSetFlags()[12] ? this.externalData : (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>) defaultValue(fields()[12]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AvroAudit>
          WRITER$ = (org.apache.avro.io.DatumWriter<AvroAudit>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
          throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AvroAudit>
          READER$ = (org.apache.avro.io.DatumReader<AvroAudit>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
          throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
