# =============================================================================
# CONNECTOR VARIABLES - PRODUCTION
# =============================================================================
# Aplicación: PEVE
# Entorno: Production (PRO)
# Última actualización: 2024-01-XX
# Responsable: [Nombre del equipo]

# =============================================================================
# CONNECTOR CONFIGURATION (Non-Sensitive) - Environment Specific
# =============================================================================
config_nonsensitive:
  salesforce.platform.event.name: "prod-platform-event-name"
  salesforce.instance: "prod-instance.salesforce.com"
  topics: "prod-topic-name"

# =============================================================================
# CONNECTOR CONFIGURATION (Sensitive) - Environment Specific
# =============================================================================
config_sensitive:
  salesforce.username: ""  # Se obtiene desde Vault/secrets
  salesforce.password: ""  # Se obtiene desde Vault/secrets
  salesforce.consumer.key: ""  # Se obtiene desde Vault/secrets
  salesforce.consumer.secret: ""  # Se obtiene desde Vault/secrets

# =============================================================================
# CONNECTOR STATUS
# =============================================================================
status: "RUNNING"

