# =============================================================================
# CONNECTOR VARIABLES - PRODUCTION
# =============================================================================
# Aplicación: PEVE
# Entorno: Production (PRO)

# =============================================================================
# CONNECTOR CONFIGURATION (Non-Sensitive) - Environment Specific
# =============================================================================
config_nonsensitive:
  kafka.topic: "prod-peve-datagen-orders"

# =============================================================================
# CONNECTOR CONFIGURATION (Sensitive) - Environment Specific
# =============================================================================
# Datagen no requiere credenciales sensibles
config_sensitive: {}

# =============================================================================
# CONNECTOR STATUS
# =============================================================================
status: "RUNNING"

# =============================================================================
# METADATA (Opcional - para referencia)
# =============================================================================
# =============================================================================
# VAULT REFERENCES
# =============================================================================
vault:
  service_account: "SA_AZC_PRO_PEVE_DATAGEN_01"

project: "PEVE"
recipients: dennispaitan@bcp.com.pe
hosted: ccloud
api-key-sequence: "01"
