name: "event driven resources"
description: "Event Driven Catalog"
inputs:
  CODAPP:
    required: true
  RELATIVE_SUBPATH_SRC:
    required: true
  TF_RELATIVE_SUBPATH:
    required: true
  HV_PEVE_SECRETS:
    required: true
  PATH_CAROOT:
    required: true
  ENV:
    required: true
  STORAGE_ACCOUNT_NAME:
    required: true
  CC_SR_PROPERTIES:
    required: true
  JOB_STAGE:
    required: true

runs:
  using: "composite"
  steps:
    - name: TF catalog
      shell: bash
      env:
        SSL_CERT_FILE: ${{ inputs.PATH_CAROOT }}
      run: |
        yq --version
        mkdir -p "${{ inputs.RELATIVE_SUBPATH_SRC }}/${{ inputs.CODAPP }}/governance"

        pwd
        files=$(ls "${{ inputs.RELATIVE_SUBPATH_SRC }}/${{ inputs.CODAPP }}/governance/"catalog-*-tags.yaml 2>/dev/null || echo "")
        if [ -z "$files" ]; then
          echo "No se encontraron archivos que coincidan con el patrón 'catalog-*-tags.yaml'."
          exit 0
        fi

        export HV_PEVE_SECRETS='${{ inputs.HV_PEVE_SECRETS }}'
        export ARM_ACCESS_KEY=$( echo $HV_PEVE_SECRETS |jq -r ".PEVE_GHA_ARM_ACCESS_KEY")
    

        for file in $files; do
          echo ""
          echo ""
          echo ""
          echo "********************************************************************************************************************************* "

          content=$(cat $file)
          properties_sr_name=$(echo "$content" | yq '.environment.catalog_management.properties[0].name')
          
          echo '${{ inputs.CC_SR_PROPERTIES}}' > cc_sr_properties.json
          echo "Imprimir contenido del archivo cc_sr_properties.json"
          cat cc_sr_properties.json
          echo "validar JSON cc_sr_properties.json"
          cat cc_sr_properties.json | jq .

          export baseFilename=$(basename "$file")
          echo "baseFilename: $baseFilename"

          ls -lia ./automation
          rm -rf ./automation/catalog_management.tf

          chmod +x ./automation/scripts/gen_catalog_management_dinamic.sh
          ./automation/scripts/gen_catalog_management_dinamic.sh "${{ inputs.CODAPP }}" "${{ inputs.RELATIVE_SUBPATH_SRC }}" "$baseFilename"

          CLUSTER_TYPE="cc"
          schema_registry_id=$(jq -r ".${properties_sr_name}.schema_registry_id" cc_sr_properties.json)
          schema_registry_rest_endpoint=$(jq -r ".${properties_sr_name}.schema_registry_rest_endpoint" cc_sr_properties.json)

          echo "Obtener el SR API KEY SECRET SCHEMA REGISTRY - Properties: .${properties_sr_name}"
          schema_registry_api_key=$( echo $HV_PEVE_SECRETS |jq -r ".${properties_sr_name}_api_key")
          schema_registry_api_secret=$( echo $HV_PEVE_SECRETS |jq -r ".${properties_sr_name}_api_secret")

          echo "CLUSTER_TYPE: $CLUSTER_TYPE"
          
          export TF_VAR_sr_id=$schema_registry_id
          export TF_VAR_sr_rest_endpoint=$schema_registry_rest_endpoint
          export TF_VAR_sr_api_key=$schema_registry_api_key
          export TF_VAR_sr_api_secret=$schema_registry_api_secret

          echo "Archivo: $file"
          echo "properties_sr_name: $properties_sr_name"
          echo "schema_registry_id: $schema_registry_id"
          echo "schema_registry_rest_endpoint: $schema_registry_rest_endpoint"

          pwd
          rm -f ./automation/backend.hcl
          rm -f ./automation/.terraform.lock.hcl
          rm -rf ./automation/.terraform
        cat <<EOF > ./automation/backend.hcl
        storage_account_name   = "${{ inputs.STORAGE_ACCOUNT_NAME }}"
        container_name         = "tf-peve-resources"
        key                    = "${{ inputs.ENV }}/${{ inputs.CODAPP }}/${CLUSTER_TYPE}/tf-${properties_sr_name}-catalog.tfstate"
        EOF
          ls -lia ./automation
          cat ./automation/backend.hcl
          terraform -chdir=./automation init -backend-config=backend.hcl 
          terraform -chdir=./automation validate

          if [[ ${{ inputs.JOB_STAGE }} == "CD" ]]; then
            echo "**********************  CD  **********************"
            terraform -chdir=./automation apply --auto-approve
          elif [[ ${{ inputs.JOB_STAGE }} == "CI" ]]; then
            terraform -chdir=./automation plan
          fi

        done


