# Terraform event-driven (Connect, Flink, EDA, …).
# No orquesta create/delete/start: eso es plan|apply|destroy en PEVE-event-driven-resources-v2.
.DEFAULT_GOAL := help

include make/variables.mk
include make/help.mk
include make/lint.mk
include make/test.mk
include make/stacks.mk
include make/eda-core.mk
