---
- name: Login to oc master
  shell: oc login -u {{ external_registry_username }} -p {{ external_registry_password }} {{ master_ocp_url }} --insecure-skip-tls-verify
  when: hosted_on == 'ocp'
  no_log: False

- name: Login to azure
  shell: az login --service-principal --username {{ aks_service_principal }} --tenant {{ az_tenant }} --password {{ aks_certificate }}
  when: hosted_on == 'aks'
  no_log: True

- name: Insert Values to ServiceAccount 
  template:
    src: "service-account.j2"
    dest: "{{ workspace }}/devops/deploy/service-account.yaml"
    force: yes
  when: hosted_on == 'ocp'

- name: Lists Configmaps for Kafka Connect Configuration
  shell: "{{ client_k8s }} -n {{ namespace }} get serviceaccounts -o name"
  register: serviceaccounts
  when: hosted_on == 'ocp'

- name: Delete Service Account
  shell: "{{ client_k8s }} -n {{ namespace }} delete serviceaccounts {{ kafkaConnectName }}"
  when: (hosted_on == 'ocp') and ( 'serviceaccount/{{ kafkaConnectName }}' in serviceaccounts.stdout.split() )
  
- name: Get AKS Credentials
  shell: az aks get-credentials --resource-group {{ aks_rg }} --name {{ aks_cluster }} -a
  when: hosted_on == 'aks'
  no_log: False

- name: "Copy kubeconfig to /tmp/{{ inventory_hostname }}_config"
  copy:
    src: "~/.kube/config"
    dest: "/tmp/{{ inventory_hostname }}_config"
  when: hosted_on == 'aks'

- name: Check jks secrets
  shell: "{{ client_k8s }} -n {{ namespace }} get secrets -o name | grep -i \"{{ credentialId  }}\"" 
  register: secrets_jks
  when: credentialId is defined
  failed_when: "secrets_jks.rc >= 2"

- name: Delete JKS Secrets
  shell: "{{ client_k8s }} -n {{ namespace }} delete {{ item }}"
  with_items:
  - "{{ secrets_jks.stdout_lines }}"
  when: credentialId is defined and secrets_jks.rc <= 2 
  
- name: Check logstash certs secrets
  shell: "{{ client_k8s }} -n {{ namespace }} get secrets -o name | grep -i \"{{ credentialId }}-cert-logstash\"" 
  register: secrets_logstash
  when: credentialId is defined
  failed_when: "secrets_logstash.rc >= 2"
  no_log: False

- name: Delete logstash certs Secrets
  shell: "{{ client_k8s }} -n {{ namespace }} delete {{ item }}"
  with_items:
  - "{{ secrets_logstash.stdout_lines }}"
  when: credentialId is defined and secrets_logstash.rc <= 2 

- name: Create Service Account
  shell: "{{ client_k8s }} -n {{ namespace }} apply -f {{ workspace }}/devops/deploy/service-account.yaml"
  when: hosted_on == 'ocp'

- name: Create Confluent Security Master Key
  shell: "{{ client_k8s }} -n {{ namespace }} create secret generic {{ confluentSecurityMasterKeyName }} --from-file={{ confluentSecurityMasterKeySecretKey }}={{ workspace }}/{{ confluentSecurityMasterKeyFilePath }}"
  when: confluentSecurityMasterKeyName is defined

- name: Label Confluent Security Master Key
  shell: "{{ client_k8s }} -n {{ namespace }} label secrets {{ confluentSecurityMasterKeyName}} project={{ namespace }}"
  when: confluentSecurityMasterKeyName is defined

- name: Create Confluent Secret File Encrypted
  shell: "{{ client_k8s }} -n {{ namespace }} create secret generic {{ confluentSecretFileEncryptedName }} --from-file={{ workspace }}/{{ confluentSecretFileEncryptedPath }}"
  when: confluentSecretFileEncryptedName is defined

- name: Label Confluent Secret File Encrypted
  shell: "{{ client_k8s }} -n {{ namespace }} label secrets {{ confluentSecretFileEncryptedName }} project={{ namespace }}"
  when: confluentSecretFileEncryptedName is defined

- name: Create Confluent Secret Config File
  shell: "{{ client_k8s }} -n {{ namespace }} create secret generic {{ confluentSecretConfigFileName }} --from-file={{ workspace }}/{{ confluentSecretConfigFilePath }}"
  when: confluentSecretConfigFileName is defined

- name: Label Confluent Secret Config File
  shell: "{{ client_k8s }} -n {{ namespace }} label secrets {{ confluentSecretConfigFileName }} project={{ namespace }}"
  when: confluentSecretConfigFileName is defined

